<?php

namespace AppBundle\Entity;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPossibleParents($id)
    {
        $id = intval($id);
        $query = 'SELECT p FROM AppBundle:Pages p ';
        if (isset($id) && $id >= 0) {
            $query .= 'where p.id != ' . $id;
        }
        return $this->getEntityManager()->createQuery($query)->getResult();
    }

    /**
     * Return Top pages data needed for generating menus
     * @return array
     */
    public function findTopPages()
    {
        $query = 'SELECT p.id, p.menuTitle FROM AppBundle:Pages p where p.parent IS NULL';
        return $this->getEntityManager()->createQuery($query)->getResult();
    }

    /**
     * Return Sub pages of page with choosen id returns data needed for generating menus
     * @return array
     */
    public function findSubPages(int $id)
    {
        $query = 'SELECT p.id, p.menuTitle FROM AppBundle:Pages p where p.parent =' . $id;
        return $this->getEntityManager()->createQuery($query)->getResult();
    }

    /**
     * Returns number of all pages
     * @return integer
     */
    public function countAll()
    {
        $query = 'SELECT COUNT(p) FROM AppBundle:Pages p';
        return $this->getEntityManager()->createQuery($query)->getSingleScalarResult();
    }
}
